apiVersion: v1
kind: Service
metadata:
  name: ecoloop-backend-service
spec:
  selector:
    app: ecoloop-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer